//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberBülteniAPİ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haber()
        {
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int haberId { get; set; }
        public string haberBaslik { get; set; }
        public string haberOzet { get; set; }
        public string haber { get; set; }
        public string haberFoto { get; set; }
        public int haberYazarId { get; set; }
        public int haberKategoriId { get; set; }
        public string haberTarih { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Yazar Yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
